site_name: Python爬虫工程师指南
site_description: Python爬虫工程师指南
site_author: 梧桐
copyright: 梧桐
site_url: https://crawl.tplan.cc
repo_url: https://github.com/PY-GZKY/CrawlEngineerGuide
repo_name: PY-GZKY/CrawlEngineerGuide
remote_name: https://github.com/PY-GZKY/CrawlEngineerGuide
remote_branch: site

theme:
  name: 'material'
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  language: 'zh'
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 打开深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-outline
        name: 关闭深色模式

extra:
  search:
  analytics:
    provider: google
    property: 'UA-111276663-2'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.critic
  - toc:
      permalink: false

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.number.min.js

nav:
  - 首页:
      - 首页: README.md

  - app逆向:
      - app逆向的一般流程: app123.md

  - 爬虫基础:
        - 爬虫抓包的选择: 爬虫抓包的选择.md
        - 抓不到包的时候应该怎么办: 抓不到包的时候应该怎么办.md
        - 通用的App爬虫流程: 通用的App爬虫流程.md
        - 反编译小程序: 反编译小程序.md
        - 反编译小程序: 反编译小程序.md
        - 相关工具: 相关工具.md
        - 逆向神器之Frida: 逆向神器之Frida.md
        - 逆向神器之Xposed: 逆向神器之Xposed.md
