site_name: Python爬虫工程师指南
site_description: Python爬虫工程师指南
site_author: 梧桐
copyright: 梧桐
site_url: https://crawl.tplan.cc
repo_url: https://github.com/PY-GZKY/CrawlEngineerGuide
repo_name: PY-GZKY/CrawlEngineerGuide
remote_name: https://github.com/PY-GZKY/CrawlEngineerGuide
remote_branch: site

theme:
  name: 'material'
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  language: 'zh'
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 打开深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-outline
        name: 关闭深色模式

extra:
  search:
  analytics:
    provider: google
    property: 'UA-111276663-2'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.critic
  - toc:
      permalink: false

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.number.min.js


plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - 首页:
      - 首页: README.md

  - 爬虫基础:
      - 爬虫抓包顺序的选择: 爬虫抓包顺序的选择.md
      - 抓不到包的时候应该怎么办: 抓不到包的时候应该怎么办.md
      - 无限Debug绕过方案: 无限Debug绕过方案.md
      - 在进行爬虫任务时应该选择多进程还是多线程: 在进行爬虫任务时应该选择多进程还是多线程.md

  - 网页自动化:
      - 自动化+接口拦截方案的实现: 自动化+接口拦截方案的实现.md

  - 数据存储:
      - 数据库的选择: 关于数据存储.md
      - 应该怎么把数据存到数据库: 应该怎么把数据存到数据库.md
      - 并发任务时应该如何使用数据库连接: 并发任务时应该如何使用数据库连接.md

  - app逆向:
      - app爬虫的一般流程: app爬虫的一般流程.md
      - 实战app爬虫的过程: 实战app爬虫的过程.md
      - 反编译小程序: 反编译小程序.md
      - 逆向过程相关工具: 逆向过程相关工具.md
      - 逆向神器之Frida: 逆向神器之Frida.md
      - 逆向神器之Xposed: 逆向神器之Xposed.md

  - app群控:
      - app群控方案选择: app群控方案选择.md
      - app群控的准备工作: app群控的准备工作.md
      - appium群控框架: appium群控框架.md
      - appium使用教程: appium使用教程.md
      - uiautomator2使用教程: uiautomator2使用教程.md
      - 安卓手机设置VPN代理: 安卓手机设置VPN代理.md


  - 爬虫管理:
      - 搭建爬虫管理后台: 爬虫管理后台搭建过程.md